name: build
on: [push]
permissions:
  checks: write
  contents: read
  packages: read
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang-tidy clang-tools
          version: 1.0
      - uses: actions/checkout@v4.2.2
      - name: Build and run tests
        run: bash ci.sh -xe
      - name: Build annotations
        if: always()
        uses: yuzutech/annotations-action@v0.5.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: annotations (build)
          input: diagnostics.json
      - name: clang-tidy annotations
        if: always()
        uses: yuzutech/annotations-action@v0.5.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: annotations (clang-tidy)
          input: tidy-annotations.json
